CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS chat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  created_at TEXT NOT NULL,
  is_group BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS association (
  user_id INTEGER NOT NULL,
  chat_id INTEGER NOT NULL,
  join_at TEXT NOT NULL,
  PRIMARY KEY (user_id, chat_id),
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS message (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content TEXT NOT NULL,
  sender_id INTEGER NOT NULL,
  chat_id INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (sender_id) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS request (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id INTEGER NOT NULL,
  inviter_id INTEGER NOT NULL,
  invitee_id INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE,
  FOREIGN KEY (inviter_id) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (invitee_id) REFERENCES user(id) ON DELETE CASCADE
);